/**
 * Generates dist/tokens.css from tokens.json: CSS custom properties, with the
 * same light/dark structure as the approved home screen mockup, so every
 * consumer (web now, anything else later) styles off the exact same values.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import tokens from "../src/tokens.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, "../dist");

function kebab(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function colorVars(mode: "light" | "dark"): string {
  return Object.entries(tokens.color[mode])
    .map(([key, value]) => `  --${kebab(key)}: ${value};`)
    .join("\n");
}

const css = `/* Generated by packages/tokens/scripts/gen-css.ts - do not edit by hand. */
:root {
${colorVars("light")}
  --radius-xs: ${tokens.radius.xs};
  --radius-sm: ${tokens.radius.sm};
  --radius-md: ${tokens.radius.md};
  --radius-lg: ${tokens.radius.lg};
  --radius-xl: ${tokens.radius.xl};
  --radius-pill: ${tokens.radius.pill};
  --font-display: ${tokens.font.display};
  --font-ui: ${tokens.font.ui};
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars("dark")}
  }
}

:root[data-theme="dark"] {
${colorVars("dark")}
}

/* Per-puzzle signature color (PRD: "one signature color per puzzle"), scoped via
   [data-puzzle] rather than [data-theme] so it composes independently of light/dark. */
[data-puzzle="starfield"] { --c: var(--violet); --cd: var(--violet-deep); --cs: var(--violet-soft); }
[data-puzzle="shiftword"] { --c: var(--orange); --cd: var(--orange-deep); --cs: var(--orange-soft); }
[data-puzzle="unblock"] { --c: var(--teal); --cd: var(--teal-deep); --cs: var(--teal-soft); }
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(path.join(OUT_DIR, "tokens.css"), css);
console.log(`Wrote ${path.join(OUT_DIR, "tokens.css")}`);
